language: php

php: [5.4, 5.5, 5.6, hhvm-nightly]

matrix:
  allow_failures:
    - php: hhvm-nightly

before_script:
  - composer selfupdate
  - composer install --prefer-source

script:
  - find tests/ -name "*Test.php" | php fastest -v
  - bin/behat --config=adapters/Behat2/behat.yml
  - sed -i -e 's/"behat\/behat"\x3A "~.*/"behat\/behat"\x3A "~3"/' composer.json
  - composer update --prefer-source
  - bin/behat --config=adapters/Behat/behat.yml
