language: php

php: [5.4, 5.5, 5.6, hhvm]

services:
  - redis-server

before_script:
  - composer selfupdate
  - composer install --prefer-source

script:
  - find tests/ -name "*Test.php" | php fastest.php parallel